# optional: bool,
# optional_with: Option<Vec<String>>,
# version: Option<VersionReq>,
# on_level: DepOnLevel,
# collection: PackageType,

[[dependency.sh]]
optional = false
level = "Node"
collection = "Executor"